### ISSUE TITLE
URL shortcuts do not load the the browser correctly

### ISSUE THREAD

**Issue by yampeku** [IHTSDO/sct-browser-frontend#36]
URL shortcuts seem to be broken. Using the example provided ([http://browser.ihtsdotools.org/index.html?perspective=full&conceptId1=195967001&edition=en-edition&release=v20140731&langRefset=900000000000509007](http://browser.ihtsdotools.org/index.html?perspective=full&conceptId1=195967001&edition=en-edition&release=v20140731&langRefset=900000000000509007)) shows a "Error while retrieving data from server.

Any combination of parameters I have tried give similar results.

**Comment by rorydavidson** [comment]
Thanks for the feedback, the example has now been updated for the correct URL.
