### ISSUE TITLE
The website is down today: http://browser.ihtsdotools.org/

### ISSUE THREAD

**Issue by Shane-Neeley** [IHTSDO/sct-browser-frontend#41]
Hi, Just letting you know I noticed your site and API is down. It was working yesterday Jan 2nd.

**Comment by rorydavidson** [comment]
Thanks, but it's working ok from here and we have no other reports of any downtime. What URL are you using for the API and site?

**Comment by Shane-Neeley** [comment]
Thanks Rory. Is it possible my IP address was blacklisted for concurrent requests?

These are errors for me.
http://browser.ihtsdotools.org 
http://browser.ihtsdotools.org/api/v2/snomed/en-edition/v20170731/concepts/79859009

<img width="686" alt="screen shot 2018-01-03 at 9 23 54 pm" src="https://user-images.githubusercontent.com/2942715/34551220-81b5703e-f0cc-11e7-867a-3a082947894d.png">

**Comment by rorydavidson** [comment]
It could well be because the API is rate limited as our hosted version is only available for development or reference, and not in live/production environments. If you want send an email with your IP address to our support, techsupport@snomed.org, we can investigate.
