### ISSUE TITLE
Duplicated search results

### ISSUE THREAD

**Issue by alanruttenberg** [IHTSDO/sct-browser-frontend#42]
Consider a search for "Skin and mucous membrane disorder of mouth, lips and tongue"
Two results are returned which differ only in that they are synonyms - the two results are for the same concept. 

This duplication clutters search results, making search less effective.

**Comment by rorydavidson** [comment]
If you select the 'group by concept' under options to the left of the search input, this will only show the concepts and not all the matching descriptions. 

What you are seeing in that result are the two synonyms, one is the fully specified name with the semantic tag, and the other the preferred term. Within SNOMED CT, these count as different descriptions.
