### ISSUE TITLE
Case of search failing

### ISSUE THREAD

**Issue by alanruttenberg** [IHTSDO/sct-browser-frontend#43]
A search for "pT3: Tumor invades any of the following: bone of the posterior wall of maxillary sinus, subcutaneous tissues, floor or medial wall of orbit, pterygoid fossa, ethmoid sinuses (maxillary sinus) (finding)" fails, but it is the full specified name for sctid 396617001

**Comment by kaicode** [comment]
It looks like the brackets around "maxillary sinus" are confusing the search algorithm.
I would recommend stripping any brackets apart from those around the semantic tag to get a match when using this search API.

The backend API (sct-snapshot-rest-api) will soon be deprecated so it's unlikely this will be fixed.

**Comment by rorydavidson** [comment]
This now works since the rewrite of the backend API.
