### ISSUE TITLE
Legend for icons used

### ISSUE THREAD

**Issue by qodrinzo** [IHTSDO/sct-browser-frontend#44]
What is the meaning behind and the difference between the two yellow circular icons beside each term?

![image](https://user-images.githubusercontent.com/9105400/64480400-414bae80-d1dc-11e9-9fe7-7b7e584ced86.png)

**Comment by kaicode** [comment]
Hi @qodrinzo,

Two different icons are used to show the definition status of the concept's modelling or relationships.

The clear icon is used for concepts with primitive definition status.
The concept for this definition status is 900000000000074008 |Not sufficiently defined by necessary conditions definition status (core metadata concept)|

The icon with three lines is used for concepts with a defined definition status.
The concept for this definition status is 900000000000073002 |Sufficiently defined by necessary conditions definition status (core metadata concept)|

This is the same as Primitive and Defined Class status in OWL Ontologies.
