### ISSUE TITLE
How to run the docker version with Snowstorm

### ISSUE THREAD

**Issue by sidharthramesh** [IHTSDO/sct-browser-frontend#45]
I am trying to run this with docker-compose. Snowstorm is running on a container named snowstorm.
I've edited my `docker/nginx.conf`
```
...
        location /snowstorm/ {
            proxy_pass http://snowstorm:8080;
        }

        location /ecl/ {
            proxy_pass https://dev-snowstorm.ihtsdotools.org/snowstorm/snomed-ct/v2/;
        }
...
```
This does not seem to work. Please help!

**Comment by rorydavidson** [comment]
Duplicate of #46 - Fixed now in commit on that issue.
