### ISSUE TITLE
Question about /authoring-services/ui-configuration

### ISSUE THREAD

**Issue by angelo-di-marzio** [IHTSDO/sct-browser-frontend#51]
I'm running the browser locally with snowstorm inside a docker-compose. I have access to the ui but i get a 404 for :  `GET /authoring-services/ui-configuration`

And on the server logs : 

`2020/05/14 13:46:45 [error] 6#6: *3 open() "/usr/share/nginx/html/authoring-services/ui-configuration" failed (2: No such file or directory), client: 172.22.0.1, server: , request: "GET /authoring-services/ui-configuration HTTP/1.1", host: "127.0.0.1", referrer: "http://127.0.0.1/`

I don't see those files in the repo. Am i missing something ?

Thanks for the help !

**Comment by kaicode** [comment]
Hi there. The browser makes speculative calls to some URLs to check how it should behave. That file is only required when using the browser as part of an authoring environment. For viewing SNOMED CT it's not needed.
Cheers.

**Comment by angelo-di-marzio** [comment]
Oh ok.

Thank you !
