### ISSUE TITLE
How to get release name to show up ?

### ISSUE THREAD

**Issue by Myu-Unix** [IHTSDO/sct-browser-frontend#52]
Hello,

I have the sct-browser working fine with a Snowstorm 4.8.0 instance on a docker-compose but the release name doesn't show up/shows up as "undefined".

![image](https://user-images.githubusercontent.com/1077135/82329561-c8932800-99e1-11ea-9c78-486c56c3d09f.png)

Is there a way to fix this behaviour and make it nicer ? 

Any pointers appreciated !

Cheers

**Comment by rorydavidson** [comment]
Hi, 
it looks as if you have not populated the name attribute in the codesystem (for example see - [the US CodeSystem on the public SNOMED CT browser](https://temp-snowstorm.ihtsdotools.org/snowstorm/snomed-ct/codesystems/SNOMEDCT-US)).

If you update the codesystem, you should then see the name appear in the dropdown and the blue buttons on the landing page.

**Comment by Myu-Unix** [comment]
Indeed, that solved my issue, thanks Rory 😊
