### ISSUE TITLE
unable to query concepts with valid ids that are in browser.ihtsdotools.org 

### ISSUE THREAD

**Issue by DSLituiev** [IHTSDO/sct-browser-frontend#54]
I am using the example of python API and plain browser request for several terms, e.g. id: [365508006](https://browser.ihtsdotools.org/?perspective=full&conceptId1=365508006&edition=MAIN/SNOMEDCT-US/2020-03-01&release=&languages=en)

with snowstorm however, I am not able to retrieve this term:

[https://browser.ihtsdotools.org/snowstorm/snomed-ct/MAIN/2019-07-31/descriptions/365508006](https://browser.ihtsdotools.org/snowstorm/snomed-ct/MAIN/2019-07-31/descriptions/365508006)

```
error:"NOT_FOUND"
message:"Description not found"
```

Am I missing something?

**Comment by rorydavidson** [comment]
You are querying for descriptions which have a different SNOMED CT identifier.

Instead use the `concepts` endpoint, e.g. - https://browser.ihtsdotools.org/snowstorm/snomed-ct/MAIN/2019-07-31/concepts/365508006

**Comment by DSLituiev** [comment]
Thank you.
How do I know that it is "different" and different from what?
I am trying to find children nodes through an API request. What query should I use?

**Comment by rorydavidson** [comment]
The 'unit of work' in SNOMED CT are concepts, and concepts have at least two descriptions, as well as relationships and attributes. All of these components have identifiers, but the one that you would see in healthcare records would be concept identifiers. I would recommend having a read of the SNOMED CT starter guide - http://snomed.org/starter - for more information on SNOMED CT.

To find all the child nodes, or descendants as they are referred to in SNOMED CT try the following - https://browser.ihtsdotools.org/snowstorm/snomed-ct/MAIN/2019-07-31/concepts/365508006/descendants
