### ISSUE TITLE
Is it possible to somehow reference the "latest" version of a certain edition?

### ISSUE THREAD

**Issue by gadeynebram** [IHTSDO/sct-browser-frontend#64]
Currently I have some references in a project to the online SNOMED-CT browser. The edition always contains a date.

e.g. https://browser.ihtsdotools.org/?perspective=full&conceptId1=371907003&edition=MAIN/SNOMEDCT-BE/2021-03-15&release=&languages=en,fr,nl

It would be great if I could reference something like edition=MAIN/SNOMEDCT-BE/latest. Is something like this possible?

**Comment by kaicode** [comment]
This is not currently possible but I like this idea. Marking as a feature request.

**Comment by kaicode** [comment]
Ah, wrong repository, this could go into Snowstorm as a feature request.
