### ISSUE TITLE
Showing axioms as relationships

### ISSUE THREAD

**Issue by vigiso** [IHTSDO/sct-browser-frontend#71]
Hi,

Since the International Edition RF2 release don't include active stated relationships, I would like to know how axioms are showed on both Details and Diagram tabs as relationships. May be the owl-to-stated OWL tool is being used?

Thank you,
Vicente

**Comment by kaicode** [comment]
Hi @vigiso, I'm sorry your question was not picked up sooner, I am now watching this repo.

Yes, the Snowstorm API that drives the browser is using an Axiom to Relationships function provided by the [SNOMED OWL Toolkit](https://github.com/IHTSDO/snomed-owl-toolkit) library. 

Note that some concepts have multiple axioms so the old stated relationship file format is not suitable for distributing the new axioms. There are also GCI, transitive, reflexive and property chain axioms that can not be expressed as stated relationships.
There is a hidden command line function in the toolkit (mentioned [here](https://github.com/IHTSDO/snomed-owl-toolkit/issues/35#issuecomment-573610624)) that can output something similar to a subset of the stated relationship file but that has limited use.
